### ISSUE TITLE
What to do with new_world branch

### ISSUE THREAD

**Issue by esc** [ImmobilienScout24/yamlreader#2]
There is an unmerged branch here:

https://github.com/ImmobilienScout24/yamlreader/tree/new_world

@schlomo @snordhausen @mriehl

**Comment by esc** [comment]
Seems like it is at least partially a conversion to pybuilder?

**Comment by esc** [comment]
Also, it seems like the ``target`` directory has been checked in..

**Comment by mriehl** [comment]
I say trash it - the project is very simple and code is mostly frozen due to feature-completeness. There's too much work required to make the branch usable and it's just not worth it.

**Comment by schlomo** [comment]
I see a value in a yamlreader CLI tool that just pretty prints the merged
YAML.

So far I use `python -Myamlreader ...`to check my YAML configs.

Having yamlreader as Pypi installable would solve both problems: Have
yamlreader as library and simple way to install the CLI tool.

**Comment by mriehl** [comment]
To clarify: I meant trash the branch (new_world), not the tool. I also see value in the yamlreader project being on PyPi as a standalone.

**Comment by esc** [comment]
Is there nothing in the ``new_world`` branch worth keeping, it seems to have a different implementation of the yamlreader.

**Comment by mriehl** [comment]
Afaik it's just the old implementation.

**Comment by esc** [comment]
and 'old' implementation in a 'new_world' branch?!

**Comment by mriehl** [comment]
Well it's old... and the new_world wording was about the build process (setup.py -> build.py) not the functionality

**Comment by esc** [comment]
hrmpf

**Comment by daccle** [comment]
Hi Guys! 
Just trash it, it was totally unfinished.

**Comment by snordhausen** [comment]
Hi!

I just deleted the branch.
