### ISSUE TITLE
Fails to install in Travis with using Pybuilder

### ISSUE THREAD

**Issue by karolyi** [ImmobilienScout24/yamlreader#8]
Hey,

I had to remove pypy3 support from `afp-cli` because of `yamlreader` not installing on travis.

Details:
https://travis-ci.org/ImmobilienScout24/afp-cli/jobs/104594111

I did not look deeper into the problem.

**Comment by snordhausen** [comment]
I re-tested this. At least right now, it is the [cryptography library](https://travis-ci.org/ImmobilienScout24/afp-cli/jobs/187418113#L1544) that thinks Travis' version of Pypy is too old. Yamlreader installed fine, see line 661 of the log.
